version: '3.3'

services:

  redmine:
    image: redmine:3.4.6
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: '1234'
    volumes:
      - type: bind
        source: ./plugins
        target: /usr/src/redmine/plugins
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: '1234'
