version: '3.3'

services:

  redmine:
    image: redmine:3.4
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: '1234'
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: '1234'